services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - erpnext_infrastructure_volume:/workspace:cached
      - ~/.ssh:/workspace-local/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    #network_mode: service:docker-in-docker
    privileged: true

volumes:
  erpnext_infrastructure_volume:
    driver: local