services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - erpnext_infrastructure_volume:/workspace:cached
      - ~/.ssh:/workspace-local/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "/home/vscode/init.sh && sleep infinity"
    privileged: true

volumes:
  erpnext_infrastructure_volume:
    driver: local