name: CI for Devcontainer and SSH Service

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: develop-erpnext_infrastructure-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Container Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build devcontainer
        run: |
          docker-compose -f .devcontainer/docker-compose.yml build

      - name: Build ssh_container_service
        run: |
          docker-compose -f ssh_container_service/docker-compose.yml build

      - name: Start devcontainer
        run: |
          docker-compose -f .devcontainer/docker-compose.yml up -d

      - name: Start ssh_container_service
        run: |
          docker-compose -f ssh_container_service/docker-compose.yml up -d

      - name: Wait for containers to be healthy
        run: sleep 30

      - name: Test devcontainer
        run: |
          docker ps

      - name: Test ssh_container_service
        run: |
          docker exec ${SCENARIO_NAME}_erpnext_configurator_container ls -la /home/frappe

      - name: Tear down containers
        if: always()
        run: |
          docker-compose -f erpnext_container_scenario/Components/de/sut/erpnext/15.x/docker-compose.yml down